### ISSUE TITLE
[build] 文件后缀为 .jsx  转化问题

### ISSUE THREAD

**Issue by swdenglian** [areslabs/alita#13]
例如 HelloWorldRN 中将```src/a/MyChildComp.js``` 名称改为 =>```src/a/MyChildComp.jsx``` 

程序 ```alita -i HelloWorldRN -o HelloWorldRN-out ```将会转化出

```shell
MyChildComp.jsx
MyChildComp.wxmlx
MyChildComp.wxssx
MyChildCompTemplate.wxmlx
```

所有文件都多了个 ```x```,小程序无法正常识别。

**Comment by ykforerlang** [comment]
@swdenglian  是alita在处理jsx后缀的bug ，暂时可以手动 把 .jsx --> .js

**Comment by swdenglian** [comment]
> @swdenglian 是alita在处理jsx后缀的bug ，暂时可以手动 把 .jsx --> .js

👌
