### ISSUE TITLE
函数式组件 方法名和和文件名不一致的情况，在小程序端报错

### ISSUE THREAD

**Issue by dexincoder** [areslabs/alita#14]
比如： a/myFunc.js

```javascript
export default function XX(props) {}
```
会报错，但是把 XX改为 myFunc就不报错了，或者用匿名函数也不报错

**Comment by ykforerlang** [comment]
this is a bug !

**Comment by ykforerlang** [comment]
已经修复 [commit](https://github.com/areslabs/alita/commit/668bc3e1be3131374d4f2d17ebaf8e3241501d1e) :smile::smile::smile:
