### ISSUE TITLE
pageJSON["componentGenerics"]["renderItemCPT"] 字段需为 boolean/object

### ISSUE THREAD

**Issue by 94haox** [areslabs/alita#19]
微信小程序开发助手，1.02.1907300版本
上个版本，转化后，运行正常，当前版本会报错，显示
miniprogram_npm/@areslabs/wx-react-native/component/WXFlatList/index：
pageJSON["componentGenerics"]["renderItemCPT"] 字段需为 boolean/object
pageJSON["componentGenerics"]["ListFooterComponentCPT"] 字段需为 boolean/object
pageJSON["componentGenerics"]["ListHeaderComponentCPT"] 字段需为 boolean/object
pageJSON["componentGenerics"]["ListEmptyComponentCPT"] 字段需为 boolean/object

并且 examples 中 HelloWorldRNWP 显示同样的错误

**Comment by ykforerlang** [comment]
已经修复。 更新alita版本到 1.2.1， 进入生成小程序目录，重新安装相关依赖（删除 package-lock.json, 执行 npm install ）, 构建。
