### ISSUE TITLE
目前alita已经支持Redux，请问是否有计划支持Mobx ？

### ISSUE THREAD

**Issue by mattlin** [areslabs/alita#2]
目前alita已经只支持Redux，请问是否有计划支持Mobx ？

**Comment by ykforerlang** [comment]
Alita发布之后，收到了很多咨询Mobx的问题。 所以Mobx一定是我们下阶段重点支持的

**Comment by ykforerlang** [comment]
@mattlin  mobx已经在[1.1.0](https://github.com/areslabs/alita/tree/1.1.0)版本支持， 并提供了一个样例[demo](https://github.com/areslabs/alita/tree/master/examples/RoomMobx)
