### ISSUE TITLE
为什么是基于RN，而不是React呢？

### ISSUE THREAD

**Issue by liudonghua123** [areslabs/alita#21]
如题，为什么技术选型的时候要使用React native而不是React？

**Comment by ykforerlang** [comment]
其实 不管是基于RN 还是React 其核心是一样的。 把alita扩展到React 工作量也不是太多。 但是选型主要还是考虑了内部团队的使用（我们内部有大量的RN模块），不过我们也在考虑，要不要把核心剥离开来，让大家可以自由选择RN或者React两种方式

**Comment by liudonghua123** [comment]
> 把核心剥离开来，让大家可以自由选择RN或者React两种方式

这个可以有 😃

**Comment by ykforerlang** [comment]
不过目前，alita的整体目标还是做一个 多端的解决方案。 会把react-native-web定制集成进来，最终让RN的代码，运行在类小程序，h5。 😃 😃 😃
