### ISSUE TITLE
小程序控制台报错： jsEnginScriptError  Component is not found in path 

### ISSUE THREAD

**Issue by ykforerlang** [areslabs/alita#23]
小程序控制台有类似报错：
![](https://raw.githubusercontent.com/ykforerlang/mypic/master/error.jpg)

这一般是由开发者工具引起的，解决方法是把： 重启开发者工具

**Comment by cooper1x** [comment]
重启也没有用

**Comment by ykforerlang** [comment]
@cooper1x  试试在开发者工具重新导入这个项目

**Comment by ykforerlang** [comment]
重启开发者工具如果还是报错的话，需要重新导入项目

第一步： 在开发者工具中删除项目
![](https://raw.githubusercontent.com/areslabs/alita/master/static/deleteproject.jpg)

第二步： 开发者工具重新导入这个项目
