### ISSUE TITLE
RN中使用了react-nagation，报错Uncaught Error: module "app/pages/Main/react-navigation" is not defined

### ISSUE THREAD

**Issue by gitspringcould** [areslabs/alita#25]
RN中使用了react-nagation，报错Uncaught Error: module "app/pages/Main/react-navigation" is not defined

**Comment by ykforerlang** [comment]
小程序的路由是静态的，需要特殊处理。 路由只能使用 [@areslabs/router](https://areslabs.github.io/alita/%E8%B7%AF%E7%94%B1.html)，

**Comment by gitspringcould** [comment]
好的 谢谢




------------------ 原始邮件 ------------------
发件人: "yankang"<notifications@github.com>; 
发送时间: 2019年10月9日(星期三) 晚上6:08
收件人: "areslabs/alita"<alita@noreply.github.com>; 
抄送: "何某人"<1162487568@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [areslabs/alita] RN中使用了react-nagation，报错Uncaught Error: module "app/pages/Main/react-navigation" is not defined (#25)




小程序的路由是静态的，需要特殊处理。 路由只能使用 @areslabs/router，
