### ISSUE TITLE
react 需要在配置文件extCompLibs字段指定！

### ISSUE THREAD

**Issue by gitspringcould** [areslabs/alita#26]

**Comment by ykforerlang** [comment]
先看下[alita文档](https://areslabs.github.io/alita/) :smile::smile::smile:

**Comment by gitspringcould** [comment]
这个配置文件放在什么文件夹下面呢



------------------ 原始邮件 ------------------
发件人: "yankang"<notifications@github.com>; 
发送时间: 2019年10月9日(星期三) 晚上6:10
收件人: "areslabs/alita"<alita@noreply.github.com>; 
抄送: "何某人"<1162487568@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [areslabs/alita] react 需要在配置文件extCompLibs字段指定！ (#26)




先看下alita文档 😄😄😄

**Comment by ykforerlang** [comment]
应该不需要放置，你是新的项目，还是老的项目， 老的项目可能涉及到 第三方其他库的[扩展](https://areslabs.github.io/alita/%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%84%E4%BB%B6%E5%BA%93%E6%89%A9%E5%B1%95.html),  第三方库不是直接支持的 @gitspringcould

**Comment by gitspringcould** [comment]
RN版本是0.6的是最新的



------------------ 原始邮件 ------------------
发件人: "yankang"<notifications@github.com>; 
发送时间: 2019年10月9日(星期三) 晚上6:27
收件人: "areslabs/alita"<alita@noreply.github.com>; 
抄送: "何某人"<1162487568@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [areslabs/alita] react 需要在配置文件extCompLibs字段指定！ (#26)




应该不需要放置，你是新的项目，还是老的项目， 老的项目可能涉及到 第三方其他库的扩展,  第三方库不是直接支持的 @gitspringcould

**Comment by ykforerlang** [comment]
把这个 错误截图发来看下，如果能定位到错误的代码，也截图看下吧

**Comment by gitspringcould** [comment]
就是这个




------------------ 原始邮件 ------------------
发件人: "yankang"<notifications@github.com>; 
发送时间: 2019年10月9日(星期三) 晚上6:33
收件人: "areslabs/alita"<alita@noreply.github.com>; 
抄送: "何某人"<1162487568@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [areslabs/alita] react 需要在配置文件extCompLibs字段指定！ (#26)




把这个 错误截图发来看下，如果能定位到错误的代码，也截图看下吧

**Comment by ykforerlang** [comment]
是哪个呀，老哥，你来github 回复。。。为啥你这个会有邮件的截图:smile::smile::smile:

**Comment by gitspringcould** [comment]
![无标题](https://user-images.githubusercontent.com/39726088/66474502-092dd900-eac4-11e9-89f9-3d894f2b36c3.png)

**Comment by ykforerlang** [comment]
看下app/App.js 的代码

**Comment by gitspringcould** [comment]
import React, {Fragment} from 'react'
import {SafeAreaView, StatusBar} from 'react-native'
import Main from './pages/Main/Main'

export default function App() {
    return (
        <Fragment>
            <StatusBar
                barStyle={'light-content'}
                backgroundColor={'#2C7DFF'}
            />
            <Main/>
        </Fragment>
    )
}

**Comment by ykforerlang** [comment]
@gitspringcould  更新到 v1.2.8 版本，警告/错误 发生的时候，现在会打印出文件路径。 在定位下 😅 😅 😅
