### ISSUE TITLE
RN转小程序报module "src/a/@areslabs/wx-react" is not defined 

### ISSUE THREAD

**Issue by huilv** [areslabs/alita#3]

**Comment by ykforerlang** [comment]
alita 使用了微信小程序的npm功能，需要如下图构建npm： 工具 ---> 构建npm：

![buildnpm](https://raw.githubusercontent.com/areslabs/alita/master/static/buildnpm.jpg)

一般来说报错： ‘module "xxx" is not defined’，说明npm模块没有构建好，需要点击上图构建。
