### ISSUE TITLE
alita是否有和微信小程序一样的switchTab可用？

### ISSUE THREAD

**Issue by gitspringcould** [areslabs/alita#32]
alita是否有和微信小程序一样的switchTab可用？做非Tab页跳转

**Comment by ykforerlang** [comment]
@gitspringcould  alita的router基于 [react navigation](https://reactnavigation.org/docs/en/navigation-actions.html)，需要去看下 react navigation是否支持

**Comment by ykforerlang** [comment]
alita@1.3.4版本已经支持 switchTab， history.switchTab 😄 😄 😄  。 RN端需要把@areslabs/router版本更新至1.0.4， 目标小程序目录的依赖也需要重新安装一下
