### ISSUE TITLE
关于alita一键转化时候对不能转化情况的粒度处理

### ISSUE THREAD

**Issue by penghuwan** [areslabs/alita#33]
热忱的开发者您好

现在Alita在一键转化的时候
对于那些仅仅因为包含原生平台组件而不符合要求的文件（注意是仅仅），是一律选择不转化的，就是转化后没有生成那个文件
那么能否支持这样一种特性呢：

对于包含原生平台组件（如DatePickerAndroid，ToastAndroid）等组件或API，选择忽略掉这部分组件的转化，但是文件中的其他代码还是允许转化成功的。

也就是说，把转化的粒度要求降低为“组件” 而不是“文件”

现在我们项目耦合了比较多的原生平台的代码，要直接去除成本有点高。
请问这个需求是否合理呢？想听听您的理由

**Comment by ykforerlang** [comment]
@penghuwan  现在转化的粒度是组件了， 对于不支持的“组件”会退化为一个 提示的文本信息
