### ISSUE TITLE
Alita现阶段支持TypeScript吗

### ISSUE THREAD

**Issue by penghuwan** [areslabs/alita#34]
我是这样想的
1.如果支持对TypeScript转化为Javascript的话就更好了
2.如果不支持的话，那么我这边用tsc编译工具转化一下也可以

请问知不支持呢

**Comment by ykforerlang** [comment]
会在 1.3.1 支持，马上了

**Comment by penghuwan** [comment]
好的，谢谢您

**Comment by ykforerlang** [comment]
已经支持了 1.3.1 :smile: 😄
