### ISSUE TITLE
Alita转化条件限制未来是否会放宽

### ISSUE THREAD

**Issue by penghuwan** [areslabs/alita#35]
**首先感谢贵司的软件工程师在小程序框架上所做的贡献。╭(￣▽￣)╯** 
我对Alita和Taro都保持着关注，学习和了解，同时也有一些自己的问题

Taro对于生成小程序项目的限制是比较宽的，而相对之下Alita则严格一些。以下的两个限制在贵司的Taro框架中是不需要考虑的,但在目前版本的Alita中则存在
- refs只能是函数
- 一个文件里只能有一个class组件
>
**请问它们是否也会从未来的Alita的转化限制中解除呢？**

**Comment by ykforerlang** [comment]
Alita 和Taro采用的是完全不同的设计思路，Alita解放的主要是JSX语法的能力，你可以调研一下， 我们在[这篇文章](https://areslabs.github.io/alita/%E4%B8%80%E7%A7%8D%E8%AE%A9%E5%B0%8F%E7%A8%8B%E5%BA%8F%E6%94%AF%E6%8C%81JSX%E8%AF%AD%E6%B3%95%E7%9A%84%E6%96%B0%E6%80%9D%E8%B7%AF.html) 也有说明 😄 😄 😄 ，相比Taro来说，Alita对JSX的语法支持是完善的。

* refs 现在有3种方式，字符串，函数，createRef， createRef会支持的，字符串由于React本身已经，弃用了，我们也不打算支持

* 单文件单组件的限制，未来会去除，但是现在还不在排期里面

**Comment by penghuwan** [comment]
请问一下，您说 “createRef会支持”，那请问现在已经支持了吗？ 如果尚未支持，又预计是在多久以后支持呢？ 谢谢～

**Comment by ykforerlang** [comment]
大概会和 React 16.x 的新生命周期一起支持，估计在1.3.3 或者1.3.4

**Comment by ykforerlang** [comment]
最近在弄 npm相关部分，要在等几个版本
