### ISSUE TITLE
Alita无法转换使用了react-native-elements的RN项目吗？

### ISSUE THREAD

**Issue by guyi-maple** [areslabs/alita#36]
我在examples的基础上加上了elements，转换后，小程序里会报找不到module。

**Comment by ykforerlang** [comment]
Alita现在不会对 第三方库自动处理，需要手动处理，参考文档： [npm包说明](https://areslabs.github.io/alita/npm%E5%8C%85%E8%AF%B4%E6%98%8E.html), [第三方组件库扩展](https://areslabs.github.io/alita/%E7%AC%AC%E4%B8%89%E6%96%B9%E7%BB%84%E4%BB%B6%E5%BA%93%E6%89%A9%E5%B1%95.html)

**Comment by guyi-maple** [comment]
感谢，第三方拓展以为是去拓展alita，然后我就给跳过了…………
