### ISSUE TITLE
地图组件

### ISSUE THREAD

**Issue by imhazige** [areslabs/alita#45]
重要的地图组件怎么处理？

**Comment by ykforerlang** [comment]
对于 Map ，canvas， live-pusher 这类组件。感觉去两边适配不是好办法，Alita后两个版本应该会提供 直接使用小程序组件的能力，可以：

```javascript

if (platform.os === 'wx') {
     // 微信地图组件
    <map/>
} else {
   // RN 地图组件
   <Map/>
}

```

**Comment by imhazige** [comment]
那就是说暂时不能用地图了？

**Comment by ykforerlang** [comment]
嗯，得等等。也有[手动对齐的办法](https://areslabs.github.io/alita/%E7%AC%AC%E4%B8%89%E6%96%B9%E7%BB%84%E4%BB%B6%E5%BA%93%E6%89%A9%E5%B1%95.html)，但是感觉地图组件工作量应该不少

**Comment by imhazige** [comment]
要是官方能出来适应三端的地图，那就厉害了。

**Comment by ykforerlang** [comment]
V2.4 支持对小程序组件/小程序自定义组件库的直接使用了 [详情](https://areslabs.github.io/alita/%E5%B0%8F%E7%A8%8B%E5%BA%8F%E5%86%85%E7%BD%AE%E7%BB%84%E4%BB%B6&%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%84%E4%BB%B6%E7%9A%84%E4%BD%BF%E7%94%A8.html)
