### ISSUE TITLE
对部分难以转换的部分，是否支持接入原生小程序？

### ISSUE THREAD

**Issue by yatessss** [areslabs/alita#46]
有些部分比较难适配alita的转换，如何在转换后的项目中添加原生小程序文件？在文档中没有找到答案，望解答谢谢~

**Comment by ykforerlang** [comment]
能详细说明一下吗？ 或者 举个例子呢  😅

**Comment by yatessss** [comment]
目前还没有具体场景，就是项目一部分使用rn转换的代码，一部分使用原生的小程序。这个场景在逐步迁移项目时可以能会用



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yankang <notifications@github.com&gt;
发送时间: 2020年1月7日 18:28
收件人: areslabs/alita <alita@noreply.github.com&gt;
抄送: yatessss <897969073@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[areslabs/alita] 对部分难以转换的部分，是否支持接入原生小程序？ (#46)

**Comment by ykforerlang** [comment]
如果是小程序页面的话，可以在生成的小程序目录里面建立一个 pages目录，把相应的小程序代码放置在这里，直接使用小程序页面即可。

如果仅仅是组件，会有点麻烦，React层面代码怎么import是个问题？可能需要把小程序组件 包装一下， 参考[第三方组件库扩展](https://areslabs.github.io/alita/%E7%AC%AC%E4%B8%89%E6%96%B9%E7%BB%84%E4%BB%B6%E5%BA%93%E6%89%A9%E5%B1%95.html)。 [wx-react-native](https://github.com/areslabs/alita/tree/master/packages/wx-react-native) 目录下都是alita包装过的小程序组件，用来映射RN官方组件

**Comment by yatessss** [comment]
多谢你的回复。目前有一个rn项目 想要逐步切换为小程序，小程序现有项目使用原生小程序写的，目前不清楚是否可以 还在尝试，有问题会继续和您请教



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yankang <notifications@github.com&gt;
发送时间: 2020年1月7日 18:59
收件人: areslabs/alita <alita@noreply.github.com&gt;
抄送: yatessss <897969073@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[areslabs/alita] 对部分难以转换的部分，是否支持接入原生小程序？ (#46)




如果是小程序页面的话，可以在生成的小程序目录里面建立一个 pages目录，把相应的小程序代码放置在这里，直接使用小程序页面即可。
 
如果仅仅是组件，会有点麻烦，React层面代码怎么import是个问题？可能需要把小程序组件 包装一下， 参考第三方组件库扩展。 wx-react-native 目录下都是alita包装过的小程序组件，用来映射RN官方组件

**Comment by ykforerlang** [comment]
V2.4 支持对小程序组件/小程序自定义组件库的直接使用了 [详情](https://areslabs.github.io/alita/%E5%B0%8F%E7%A8%8B%E5%BA%8F%E5%86%85%E7%BD%AE%E7%BB%84%E4%BB%B6&%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%84%E4%BB%B6%E7%9A%84%E4%BD%BF%E7%94%A8.html)
