### ISSUE TITLE
Todo demo 引入第三方包后运行报错

### ISSUE THREAD

**Issue by yatessss** [areslabs/alita#48]
在Todo demo中引入 hello-rn，在alita.config.js中添加
```js
include:[
      path.resolve('node_modules', '@areslabs', 'hello-rn')
    ],
```
运行后报错
```
./RNApp.js 32:12
Module parse failed: Unexpected token (32:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
```

**Comment by ykforerlang** [comment]
这里的 include配置，会直接设置给 内部的`alita-loaders`。 所以需要：
```javascript
const path = require('path')

module.exports = {
    include:[
        path.resolve('RNApp.js'),
        path.resolve('src'),
        path.resolve('node_modules', '@areslabs', 'hello-rn')
    ],
}
```
可参考 [webpack include](https://webpack.docschina.org/configuration/module/#rule-include)

**Comment by yatessss** [comment]
好的我稍后试一下 &nbsp;有没有考虑增加webpack &nbsp;alisa的相关配置， 现在发现有些引用相对路径不是很方便



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yankang <notifications@github.com&gt;
发送时间: 2020年1月9日 09:05
收件人: areslabs/alita <alita@noreply.github.com&gt;
抄送: yatessss <897969073@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[areslabs/alita] Todo demo 引入第三方包后运行报错 (#48)

**Comment by ykforerlang** [comment]
webpack 的alias配置方式，可以直接使用。 比如 `HelloWorldRN`里面：
```javascript
resolve: {
        alias: {
            "@areslabs/stringutil-rn": "@areslabs/stringutil-wx",
        }
    },
```

**Comment by ykforerlang** [comment]
不过，我有一个疑问， 如果是相对路径的化， RN平台怎么处理呢？

**Comment by yatessss** [comment]
好的谢谢 &nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yankang <notifications@github.com&gt;
发送时间: 2020年1月9日 09:12
收件人: areslabs/alita <alita@noreply.github.com&gt;
抄送: yatessss <897969073@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[areslabs/alita] Todo demo 引入第三方包后运行报错 (#48)

**Comment by yatessss** [comment]
可以在目录下定义一个package.json的文件规定别名，不过我还不清楚是webpack处理的还是IDE来处理的，要进一步了解下。目前用alita 觉得按文件或目录转换 &nbsp;是一个比较重要的功能



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yankang <notifications@github.com&gt;
发送时间: 2020年1月9日 09:13
收件人: areslabs/alita <alita@noreply.github.com&gt;
抄送: yatessss <897969073@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[areslabs/alita] Todo demo 引入第三方包后运行报错 (#48)




不过，我有一个疑问， 如果是相对路径的化， RN平台怎么处理呢？
