### ISSUE TITLE
编译后wx-dist内组件的路径有误

### ISSUE THREAD

**Issue by yatessss** [areslabs/alita#49]
![image](https://user-images.githubusercontent.com/13636879/72120247-4d19ce00-3392-11ea-9194-ceae1ac7a8f5.png)
如图

**Comment by ykforerlang** [comment]
组件的引入，需要在 import/require 语句就直接写明，转化引擎需要静态分析出组件路径，生成json文件， 可以看下这里 [静态限制](https://areslabs.github.io/alita/%E9%9D%99%E6%80%81%E9%99%90%E5%88%B6.html)

**Comment by yatessss** [comment]
抱歉 这里没有仔细看。我也定位到适合引入方式有关了 &nbsp;我再看下打扰了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yankang <notifications@github.com&gt;
发送时间: 2020年1月10日 10:57
收件人: areslabs/alita <alita@noreply.github.com&gt;
抄送: yatessss <897969073@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[areslabs/alita] 编译后wx-dist内组件的路径有误 (#49)




组件的引入，需要在 import/require 语句就直接写明，转化引擎需要静态分析出组件路径，生成json文件， 可以看下这里 静态限制
