### ISSUE TITLE
支持文件监听

### ISSUE THREAD

**Issue by iyang519** [areslabs/alita#5]
alita -i myproject -o myprojectwp 每次修改必须要手动输出，求支持文件监听，自动重新构建出新的输出⽂件

**Comment by ykforerlang** [comment]
watch 模式已经在规划中，会在下个版本支持。

**Comment by iyang519** [comment]
有下个版本有上线时间吗

**Comment by ykforerlang** [comment]
暂定在618之后一周左右

**Comment by ykforerlang** [comment]
规划的是双周一个小版本，但是最近支持618，可能会延迟一些。:grin::grin::grin:

**Comment by ykforerlang** [comment]
@iyang519  watch模式已经支持啦
