### ISSUE TITLE
生成模板找不到 template not found

### ISSUE THREAD

**Issue by yatessss** [areslabs/alita#50]
```js
<TouchableOpacity
          onPress={() => {
            this.props.onPress()
          }}>
            {this.props.disabled
              ? <View style={{opacity: 0.3}}>{this.props.children}</View>
              : this.props.children}
        </TouchableOpacity>
```
组件内写了类似的三目运算后，模板不会生成，编译也不会有报错

**Comment by ykforerlang** [comment]
应该不是 三目运算的问题，你把 `this.props. children` 换成 `<Text>1</Text>` 试试看， 可能是`this.props.children`的问题

**Comment by yatessss** [comment]
改为`<Text>1</Text>`是可以的不过我传入的是一段element。去掉三目运算符一段element确实是可以的。

**Comment by ykforerlang** [comment]
我看下

**Comment by ykforerlang** [comment]
@yatessss  问题定位到了，正在修复。 暂时可以
```javascript
<TouchableOpacity
          onPress={() => {
            this.props.onPress()
          }}>
            {this.props.disabled
              ? <View style={{opacity: 0.3}}>{this.props.children}</View>
              : <View>{this.props.children}</View>}
        </TouchableOpacity>
```
下面没有被JSX元素包裹的`this.props.children` 没有被识别。

**Comment by yatessss** [comment]
嗯 &nbsp;好的，不过我在尝试的时候遇到很多奇奇怪怪的报错，有时能复现有时不能 完全是一个黑盒😂😂 &nbsp;还有一点就是在编译时报错有时不打印哪个文件，我看源码有一个类似filepath的其实可以加上 &nbsp;比较好定位是哪个文件出错的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yankang <notifications@github.com&gt;
发送时间: 2020年1月11日 09:23
收件人: areslabs/alita <alita@noreply.github.com&gt;
抄送: yatessss <897969073@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[areslabs/alita] 组件内不支持三目运算符 (#50)




@yatessss  问题定位到了，正在修复。 暂时可以
 <TouchableOpacity           onPress={() =&gt; {             this.props.onPress()           }}&gt;             {this.props.disabled               ? <View style={{opacity: 0.3}}&gt;{this.props.children}</View&gt;               : <View&gt;{this.props.children}</View&gt;}         </TouchableOpacity&gt;
 
下面没有被JSX元素包裹的this.props.children 没有被识别。

**Comment by ykforerlang** [comment]
嗯。你说的对。 “奇奇怪怪的报错” 你可以加我QQ（1527997464）发我， 我应该可以定位出哪里出了问题。 filepath的确应该加上，我想一想

**Comment by yatessss** [comment]
好的，我个人理解可以把整个原理画一个简易的图，然后在dev构建时候的log打全一些，这样我们可以帮助定位问题一起修复，目前想要快速把整个流程搞明白还是挺困难的，一报错也不清楚是哪个步骤有问题，一家之言仅供参考



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yankang <notifications@github.com&gt;
发送时间: 2020年1月11日 09:56
收件人: areslabs/alita <alita@noreply.github.com&gt;
抄送: yatessss <897969073@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[areslabs/alita] 组件内不支持三目运算符 (#50)




嗯。你说的对。 “奇奇怪怪的报错” 你可以加我QQ（1527997464）发我， 我应该可以定位出哪里出了问题。 filepath的确应该加上，我想一想

**Comment by ykforerlang** [comment]
嗯。 关于原理，我有时间 整理一下，其实主要就是[一种让小程序支持JSX语法的新思路](https://areslabs.github.io/alita/%E4%B8%80%E7%A7%8D%E8%AE%A9%E5%B0%8F%E7%A8%8B%E5%BA%8F%E6%94%AF%E6%8C%81JSX%E8%AF%AD%E6%B3%95%E7%9A%84%E6%96%B0%E6%80%9D%E8%B7%AF.html)， 另外加上 小程序 实例和React实例建立关系的过程。

log会一步步完善

非常欢迎一起修复 😄 😄
