### ISSUE TITLE
不支持transform

### ISSUE THREAD

**Issue by iyang519** [areslabs/alita#54]
![image](https://user-images.githubusercontent.com/8842036/73248413-e4ce4780-41ed-11ea-8844-54a9bae82cf4.png)
![image](https://user-images.githubusercontent.com/8842036/73248666-4f7f8300-41ee-11ea-8a1d-3fd284191e10.png)
去掉后正常

**Comment by ykforerlang** [comment]
transform 属性接收一个数组， 上面的可以写为： `{transform: [{rotate: "90deg"}]}`
