### ISSUE TITLE
transition failed 

### ISSUE THREAD

**Issue by MaybeSomeone** [areslabs/alita#6]
组件SafeAreaView 没有在react-native指定

HOC 组件看起来是无法在小程序中使用
TypeError: func.body.body is not iterable

这个有点让人摸不着头脑
TypeError: Cannot read property '0' of null

**Comment by ykforerlang** [comment]
SafeAreaView 的确没有对齐。加入排期了，（我也是才发现的这个组件）。

HOC的支持存在一些限制，具体可以看[这里](https://areslabs.github.io/alita/%E9%AB%98%E9%98%B6%E7%BB%84%E4%BB%B6.html)。我们还在思考移除这些限制的方式。 

第3个问题的话， 贴一下你的代码。 我看下呢 @MaybeSomeone

**Comment by MaybeSomeone** [comment]
写了一个函数式组件，可能因为他不是类的写法
const propTypes = {
  item: PropTypes.object.isRequired
};

const DynamicLogViewerCompoent = (recieveObjec) => {
  const { props = {} } = recieveObjec;
  const {
    item = {}
  } = props;
  const {
    account,
    address,
    agent,
    platform,
    nickname,
    location
  } = item;
  return (
    <View style={style.baseViewStyle}>
      <Icon name="label-icon" size={20} color="gray" style={style.iconStyle} />
      {/* leftView */}
      <View style={style.leftViewStyle}>
        {/* 昵称 */}
        <View style={style.detailViewStyle}>
          <Text style={style.titleTextStyle}>昵称：</Text>
          <Text
            style={style.detailTextStyle}
            numberOfLines={1}
            ellipsizeMode="tail"
          >
            {nickname}
          </Text>
        </View>
        {/* 账号 */}
        <View style={style.detailViewStyle}>
          <Text style={style.titleTextStyle}>账号：</Text>
          <Text
            style={style.detailTextStyle}
            numberOfLines={1}
            ellipsizeMode="tail"
          >
            {account}
          </Text>
        </View>
        {/* IP地址 */}
        <View style={style.detailViewStyle}>
          <Text style={style.titleTextStyle}>IP地址：</Text>
          <Text
            style={style.detailTextStyle}
            numberOfLines={1}
            ellipsizeMode="tail"
          >
            {address}
          </Text>
        </View>
      </View>
      {/* rightView */}
      <View style={style.rightViewStyle}>
        {/* IP地址 */}
        <View style={style.detailViewStyle}>
          <Text style={style.titleTextStyle}>设备类型：</Text>
          <Text
            style={style.detailTextStyle}
            numberOfLines={1}
            ellipsizeMode="tail"
          >
            {agent}
          </Text>
        </View>

        {/* 平台类型 */}
        <View style={style.detailViewStyle}>
          <Text style={style.titleTextStyle}>平台类型：</Text>
          <Text
            style={style.detailTextStyle}
            numberOfLines={1}
            ellipsizeMode="tail"
          >
            {platform}
          </Text>
        </View>
        {/* 登录位置 */}
        <View style={style.detailViewStyle}>
          <Text style={style.titleTextStyle}>登录位置：</Text>
          <Text
            style={style.detailTextStyle}
            numberOfLines={1}
            ellipsizeMode="tail"
          >
            {location}
          </Text>
        </View>
      </View>
    </View>
  );
};

DynamicLogViewerCompoent.propTypes = propTypes;
export default DynamicLogViewerCompoent;

**Comment by MaybeSomeone** [comment]
import React from 'react';
import { View, Text } from 'react-native';
import PropTypes from 'prop-types';
import Icon from '../../../assets/fonts/icons';
import style from './DynamicLogViewer.style';

// const DynamicLogItemPropTypes = {
//   index: PropTypes.number.isRequired,
//   value: PropTypes.string.isRequired
// };

// const DynamicLogItem = (props) => {
//   const {
//     index,
//     value
//   } = props;
//   return (
//     <View style={[style.detailViewStyle, !index && style.topViewBorderWidth]}>
//       <Text style={style.titleTextStyle}>昵称：</Text>
//       <Text
//         style={style.detailTextStyle}
//         numberOfLines={1}
//         ellipsizeMode="tail"
//       >
//         {value}
//       </Text>
//     </View>
//   );
// };

// DynamicLogItem.protoTypes = DynamicLogItemPropTypes;

const propTypes = {
  item: PropTypes.object.isRequired
};

const DynamicLogViewer = (recieveObjec) => {
  const { props = {} } = recieveObjec;
  const {
    item = {}
  } = props;
  const {
    account,
    address,
    agent,
    platform,
    nickname,
    location
  } = item;
  return (
    <View style={style.baseViewStyle}>
      <Icon name="label-icon" size={20} color="gray" style={style.iconStyle} />
      {/* leftView */}
      <View style={style.leftViewStyle}>
        {/* 昵称 */}
        <View style={style.detailViewStyle}>
          <Text style={style.titleTextStyle}>昵称：</Text>
          <Text
            style={style.detailTextStyle}
            numberOfLines={1}
            ellipsizeMode="tail"
          >
            {nickname}
          </Text>
        </View>
        {/* 账号 */}
        <View style={style.detailViewStyle}>
          <Text style={style.titleTextStyle}>账号：</Text>
          <Text
            style={style.detailTextStyle}
            numberOfLines={1}
            ellipsizeMode="tail"
          >
            {account}
          </Text>
        </View>
        {/* IP地址 */}
        <View style={style.detailViewStyle}>
          <Text style={style.titleTextStyle}>IP地址：</Text>
          <Text
            style={style.detailTextStyle}
            numberOfLines={1}
            ellipsizeMode="tail"
          >
            {address}
          </Text>
        </View>
      </View>
      {/* rightView */}
      <View style={style.rightViewStyle}>
        {/* IP地址 */}
        <View style={style.detailViewStyle}>
          <Text style={style.titleTextStyle}>设备类型：</Text>
          <Text
            style={style.detailTextStyle}
            numberOfLines={1}
            ellipsizeMode="tail"
          >
            {agent}
          </Text>
        </View>

        {/* 平台类型 */}
        <View style={style.detailViewStyle}>
          <Text style={style.titleTextStyle}>平台类型：</Text>
          <Text
            style={style.detailTextStyle}
            numberOfLines={1}
            ellipsizeMode="tail"
          >
            {platform}
          </Text>
        </View>
        {/* 登录位置 */}
        <View style={style.detailViewStyle}>
          <Text style={style.titleTextStyle}>登录位置：</Text>
          <Text
            style={style.detailTextStyle}
            numberOfLines={1}
            ellipsizeMode="tail"
          >
            {location}
          </Text>
        </View>
      </View>
    </View>
  );
};

DynamicLogViewer.propTypes = propTypes;
export default DynamicLogViewer;

**Comment by MaybeSomeone** [comment]
``

**Comment by ykforerlang** [comment]
@MaybeSomeone 这是我们在处理函数式组件的一个bug。 暂时你可以按照下面的修改一下：

```javascript
const propTypes = {
    item: PropTypes.object.isRequired
};

export default function DynamicLogViewer(recieveObjec) {
    const { props = {} } = recieveObjec;
    // other code ...
}
DynamicLogViewer.propTypes = propTypes;
```

**Comment by MaybeSomeone** [comment]
好的 谢谢

**Comment by ykforerlang** [comment]
@MaybeSomeone  转换的bug已经修复了，不过**函数式组件需要在定义的时候导出**，[详见](https://areslabs.github.io/alita/%E5%87%BD%E6%95%B0%E5%BC%8F%E7%BB%84%E4%BB%B6.html)
