### ISSUE TITLE
为啥京东没有自己的空间库？

### ISSUE THREAD

**Issue by wu928320442** [areslabs/alita#8]
为啥京东没有自己的github仓库？ 还有单打独斗，这两个轮子（另一个jd的）都连一点jd的标记真的好吗？

**Comment by ykforerlang** [comment]
:stuck_out_tongue_closed_eyes::stuck_out_tongue_closed_eyes::stuck_out_tongue_closed_eyes: 说实话我也很想知道

**Comment by zlcook** [comment]
unbelievable
