### ISSUE TITLE
建议：flutter web转taro小程序

### ISSUE THREAD

**Issue by greatGregLiu** [areslabs/alita#9]
flutter的思路来源于react。它通过一次编写支持开发app（安卓、ios）、桌面、web程序。但是它缺乏国内小程序的支持
5月flutter web发布了，转译为标准的javascript、css、html和canvas成为了现实（dart2js）。

另外，从技术角度上看flutter转译为taro，进而通过taro支持所有平台是可行的

这样前端开发人员只要学习flutter就可以了，然后通过你们的工具转译到其他全平台

这将是伟大的创新，京东的全球首创！可以大大减轻程序员的负担，解放程序员，减少996.icu

**Comment by ykforerlang** [comment]
flutter 转小程序， alita会去调研一下的。转化都是有损的，不会100%兼容。

**Comment by greatGregLiu** [comment]
谢谢。他们已经基本实现了一套代码全平台，包括web支持，但是没有支持中国特色的小程序，所以唯一缺乏小程序的支持。这是空白

或许，可以开发一个flutter web 的package，通过这个package实现小程序的特色功能，这样兼容了flutter原有的东西，又增加了小程序的支持

**Comment by ykforerlang** [comment]
@greatGregLiu  其实我们的实现细节和Taro 还是差别很多的， 你可以看下[这里](https://areslabs.github.io/alita/%E4%B8%80%E7%A7%8D%E8%AE%A9%E5%B0%8F%E7%A8%8B%E5%BA%8F%E6%94%AF%E6%8C%81JSX%E8%AF%AD%E6%B3%95%E7%9A%84%E6%96%B0%E6%80%9D%E8%B7%AF.html)。 我们可能会做Flutter转小程序，但是近期没有打算
